### ISSUE TITLE
Doesn't work: anything I missed in installation?

### ISSUE THREAD

**Issue by PovilasKorop** [CodeWithDennis/filament-theme-inspector#17]
Wanted to shoot a review, installed with `composer require` but I don't see the tooltips.

<img width="874" alt="Screenshot 2024-10-27 at 09 09 32" src="https://github.com/user-attachments/assets/fc56f898-bdcc-473d-b10e-43301d2df0e6">

Is there some step missing in the installation (like publishing assets?) so your CSS/JS files would be found successfully?

Or maybe it's something with my configuration, but it seems to be the default Filament project. 
Debug true in .env.

**Comment by CodeWithDennis** [comment]
Hi @PovilasKorop, sorry about that! I’ve added instructions to clear the cache after installing the package. Just run `php artisan filament:upgrade`, refresh the page, and it should work.

_Normally, this command runs after post-autoload-dump, but it only does so during updates, not during installation._

Let me know if that resolved it!

**Comment by PovilasKorop** [comment]
@CodeWithDennis yup, that solved it! Thanks.
